### ISSUE TITLE
💡 RFC: Optimize chord lyric spacing. Trailing Chords & chord placement ( ie: lyrics lyric[Dsus] )

### ISSUE THREAD

**Issue by isaiahdahl** [PraiseCharts/ChordSheetJS#214]
Parent Task: https://github.com/PraiseCharts/studio/issues/32

_EDIT: Expanding the scope of this task to deal with more then just trailing chord spacing, but chord placing in general. Please read through to my last comment to get up to speed._

### Background & Motivation

When the chord is at the end of a word. There needs to be extra space between the word that the chord is attached to and the following word. Otherwise it looks like the chord is over the start of the next word.

Here is an audio clip to go along with the examples below to stress how important the spacing is. Listen how off the chord would be if it was played on the start of the 'for' lyric.

https://user-images.githubusercontent.com/23046374/180817790-59e388c8-8e54-411e-81eb-db567051f209.mov

✅ What it should do:
```
{c:Verse 1}
[D] Praying[Dsus] for a miracle,[D] thirsty[Dsus]
```
Chords Over Words (TextFormatter)
```
Verse 1
D        Dsus               D        Dsus 
  Praying     for a miracle,  thirsty
```
HTML Formated
![CleanShot 2022-07-25 at 08 22 46](https://user-images.githubusercontent.com/23046374/180815372-85f1429e-b748-4dd5-9844-a709cdecfd16.png)

❌  What it currently does
```
{c:Verse 1}
[D] Praying[Dsus] for a miracle,[D] thirsty[Dsus]
```
Chords Over Words (TextFormatter)
```
Verse 1
D       Dsus           D       Dsus
 Praying for a miracle, thirsty
```
HTML Formated
![CleanShot 2022-07-25 at 08 23 09](https://user-images.githubusercontent.com/23046374/180815413-dfb0f688-930e-46e0-8d80-c72d595355ce.png)

The TextFormatter (chords over words) doesn't look terrible, you can just tell it's not starting over the "for" word. But when it's formatted in HTML, the `Dsus` pairs up with the _for_ lyric, and then it looks wrong on the generated chart.

### Possible solutions
The current PraiseCharts solution is to add the amount of space/charachters that the chord takes up as spacing between the two words. So you can clearly tell that the chord comes before the word.

_EDIT: I though this was the current praisecharts solution, but when I looked deeper and closer, It's actually just how it's structured to render the chord lyric pairs. It generates HTML where the chord only pairs up with one word for a lyric, and if it's a trailing chord, it doesn't pair up with anything it just has a chord in a block. This pushes the next lyric over because it's in a different HTML block_

In theory, it's not necessary to stick hard to that rule as there can be some long suffixes that take up unnecessary space. But the objective is that it's clear to the player that the chord does not belong on the word that comes after. It's to be played at the end of the word it's attached to. Meaning, a max of 3-4 spaces could be enough.

**Comment by isaiahdahl** [comment]
Had an idea about how to do this and got something working this evening.

<img width="877" alt="CleanShot 2022-07-26 at 21 46 28@2x" src="https://user-images.githubusercontent.com/23046374/181163552-cf8bf74d-7283-4bfe-b2cd-e1b17e4ded29.png">

Will commit tomorrow.

**Comment by isaiahdahl** [comment]
So essentially what I've done is notice that the trailing chord leaves a space before the lyric on the next. So in the formatter I check for a space as first character, if there's a space. I render the chord as whitespace. Where there's roughly 2 spaces for each character. 

```javascript
${ each(line.items, (item) => `
  ${ when(isChordLyricsPair(item), () => `
    <div class="column">
        <div class="chord">${ renderChord(item.chords, line.key, line.transposeKey, song) + '  '}</div>
        <div class="lyrics">
          ${ when(isTrailingChord(item.lyrics), () => `
            ${renderChordAsWhiteSpace(item.chords, line.key, line.transposeKey, song)}
          `)}${ item.lyrics.trim() + ' '}
        </div>
    </div>
`) }
```

This approach would work for this use case, but in testing and really comparing the spacing difference between what we're rendering with this library and what our current library does I've found some other important differences.

Here is the chordpro for the below example
```
{c:Chorus 1 *2}
Thine is the [Gm]King - [F]dom, the power, the [Dbdim7]glo - [Dm]ry
Forever and [Gm]e - [F]ver, He finished my [Dbdim7]sto - [Dm]ry
We’re singing [Gm]free - [F/A]dom, our testi - [Dbdim7]mo - [Dm]ny
We’ll be singing for - [G13]ev - [Gm7/C]er, a - [F]men[A7(#9)/E][Dm11]
We’ll be [Dm/C]singing for - [G13]ever and [G13(#5)]ever, [Gm7/C] a - [F]men
```

ChordSheetJS
![CleanShot 2022-07-27 at 09 37 11](https://user-images.githubusercontent.com/23046374/181301962-8a8f95cf-4f46-4099-b711-2af9073af925.png)


chordprojs (our current one)
![CleanShot 2022-07-27 at 09 29 15](https://user-images.githubusercontent.com/23046374/181300350-a02c9a75-716a-4621-85ba-4d13b4168ff5.png)

I matched the CSS between the renderers for this example to show this clearer. They look almost the same.

But... notice on line 4. The lyric `We'll be singing forever, amen` 

The `F` chord falls between the word `amen` and it's not played till after the word `forever` is finished.

Notice how much clearer that is in the current PraiseCharts one compared to the chordsheetjs version. The ` a- ` looks like it's still under the `Gm7/C` chord. 

ChordSheetJS
![CleanShot 2022-07-27 at 09 37 34](https://user-images.githubusercontent.com/23046374/181302095-c6b0f232-a40d-459a-8e2f-ad378e45f300.png)

PraiseCharts Current One
![CleanShot 2022-07-27 at 09 38 19](https://user-images.githubusercontent.com/23046374/181302188-02fde3b4-ae53-455e-9a70-505bef342c90.png)

### Possible Solutions 
Now the only way I think this could be solved is by making it so a `Chord` pairs up with only one word of a lyric. That would force the next lyrics or `Chord Lyric Pair` to the next div and give it the space it needs. 

Then for the trailing chord. the chord would pair up with only a space, or pair up with nothing. Which would also force the next lyrics, or chordlyric pair to be in a successive div, giving the chord the space it needs.

**Comment by martijnversluis** [comment]
> Firstly, do you agree that the chord placement is clearer on the PraiseCharts current one?

I do!

> Now the only way I think this could be solved is by making it so a Chord pairs up with only one word of a lyric.

Although I don't like the fact this will make a parsed Song more complicated in structure, I'm afraid this is the only way to solve the issue.

**Comment by isaiahdahl** [comment]
Yea for sure I understand. It has pretty significant implications just with the number of tests written so far.

But I'm confident that this is the sort of detail that makes a difference in people's experience with a chart.
