### ISSUE TITLE
💡 RFC: Parse Metadata in a text chordsheet

### ISSUE THREAD

**Issue by isaiahdahl** [PraiseCharts/ChordSheetJS#219]
Parent Task: https://github.com/PraiseCharts/studio/issues/32
### Background & Motivation

Want to explore the idea of having metadata in a text chord sheet. 

I like the idea of markdown style frontmatter.
```
title: Honey In the Rock
key: F
---
Verse 1
D       Dsus           D       Dsus
 Praying for a miracle, thirsty
```
=
```
{title: Honey In the Rock}
{key: F}
{c:Verse 1}
[D] Praying[Dsus] for a miracle,[D] thirsty[Dsus]
```

### Possible solutions

- add this functionality to the `ChordSheetParser()`
- create a new parser that can do this. `ChordsOverWordsParser()`

**Comment by martijnversluis** [comment]
Markdown frontmatter style makes sense! 

It makes sense to have a different grammar. Converting AST to a `Song` can be reused.

**Comment by martijnversluis** [comment]
@isaiahdahl I'm currently trying to compose a grammar that can parse an entire chord sheet including the front matter.

What would you prefer:

- include the front matter parsing in the grammar, starting with basic support and extending when needed
- parse the front matter as one large string and pull in a YAML parser dependency to parse it

**Comment by isaiahdahl** [comment]
I think we should include it in the grammar. 

I think it would be ideal if the '---' was optional or not even needed. And it could grab metadata without it. That would be hard to do if it wasn't in the grammar.

What do you think the downsides are to not relying on the --- to separate it?

**Comment by martijnversluis** [comment]
Hmm I'm not sure. It would be convenient not to need it. It might result in weird corner cases though when lyrics include a colon.

But I can just try to get it to work, and we can test it with some example charts?

**Comment by isaiahdahl** [comment]
Ok let's aim for not needing it.
